### ISSUE TITLE
인천 답안지에 코드가 존재하지 않습니다.

### ISSUE THREAD

**Issue by gihyeoon** [chihungim/2021-2022-Korea-ItSkills#1]
인천 지역의 코드가 없는 파일들이 존재합니다. 검토해주시길 바랍니다.

**Comment by chihungim** [comment]
> 인천 지역의 코드가 없는 파일들이 존재합니다. 검토해주시길 바랍니다.

인천 답안은 인천 답지 레포에서 확인해주세요.
https://github.com/chihungim/2022-Incheon-Answer

**Comment by gihyeoon** [comment]
21년 것의 코드를 추가해주세요~

**Comment by chihungim** [comment]
> 21년 것의 코드를 추가해주세요~

1차적으로 작성된 답안만 올라왔기에
 미완성인 답지가 존재 할 수 있습니다.
